const stockData = [
    { id: 1, name: "Reliance Industries Ltd.", yfinName: "RELIANCE.NS" },
    { id: 2, name: "HDFC Bank Ltd.", yfinName: "HDFCBANK.NS" },
    { id: 3, name: "ICICI Bank Ltd.", yfinName: "ICICIBANK.NS" },
    { id: 4, name: "Infosys Ltd.", yfinName: "INFY.NS" },
    { id: 5, name: "Bharti Airtel Ltd.", yfinName: "BHARTIARTL.NS" },
    { id: 6, name: "ITC Ltd.", yfinName: "ITC.NS" },
    { id: 7, name: "Tata Consultancy Services Ltd.", yfinName: "TCS.NS" },
    { id: 8, name: "Larsen & Toubro Ltd.", yfinName: "LT.NS" },
    { id: 9, name: "Axis Bank Ltd.", yfinName: "AXISBANK.NS" },
    { id: 10, name: "Kotak Mahindra Bank Ltd.", yfinName: "KOTAKBANK.NS" },
    { id: 11, name: "Hindustan Unilever Ltd.", yfinName: "HINDUNILVR.NS" },
    { id: 12, name: "State Bank of India", yfinName: "SBIN.NS" },
    { id: 13, name: "Bajaj Finance Ltd.", yfinName: "BAJFINANCE.NS" },
    { id: 14, name: "Maruti Suzuki India Ltd.", yfinName: "MARUTI.NS" },
    { id: 15, name: "Asian Paints Ltd.", yfinName: "ASIANPAINT.NS" },
    { id: 16, name: "HCL Technologies Ltd.", yfinName: "HCLTECH.NS" },
    { id: 17, name: "Sun Pharmaceutical Industries Ltd.", yfinName: "SUNPHARMA.NS" },
    { id: 18, name: "Wipro Ltd.", yfinName: "WIPRO.NS" },
    { id: 19, name: "Mahindra & Mahindra Ltd.", yfinName: "M&M.NS" },
    { id: 20, name: "Nestle India Ltd.", yfinName: "NESTLEIND.NS" },
    { id: 21, name: "Tata Motors Ltd.", yfinName: "TATAMOTORS.NS" },
    { id: 22, name: "HDFC Ltd.", yfinName: "HDFC.NS" },
    { id: 23, name: "Bajaj Auto Ltd.", yfinName: "BAJAJ-AUTO.NS" },
    { id: 24, name: "Power Grid Corporation of India Ltd.", yfinName: "POWERGRID.NS" },
    { id: 25, name: "UltraTech Cement Ltd.", yfinName: "ULTRACEMCO.NS" },
    { id: 26, name: "NTPC Ltd.", yfinName: "NTPC.NS" },
    { id: 27, name: "Tata Steel Ltd.", yfinName: "TATASTEEL.NS" },
    { id: 28, name: "Tech Mahindra Ltd.", yfinName: "TECHM.NS" },
    { id: 29, name: "JSW Steel Ltd.", yfinName: "JSWSTEEL.NS" },
    { id: 30, name: "Grasim Industries Ltd.", yfinName: "GRASIM.NS" },
    { id: 31, name: "Bajaj Finserv Ltd.", yfinName: "BAJAJFINSV.NS" },
    { id: 32, name: "Hindalco Industries Ltd.", yfinName: "HINDALCO.NS" },
    { id: 33, name: "Dr. Reddy's Laboratories Ltd.", yfinName: "DRREDDY.NS" },
    { id: 34, name: "Cipla Ltd.", yfinName: "CIPLA.NS" },
    { id: 35, name: "Britannia Industries Ltd.", yfinName: "BRITANNIA.NS" },
    { id: 36, name: "Adani Ports and Special Economic Zone Ltd.", yfinName: "ADANIPORTS.NS" },
    { id: 37, name: "Oil & Natural Gas Corporation Ltd.", yfinName: "ONGC.NS" },
    { id: 38, name: "Divi's Laboratories Ltd.", yfinName: "DIVISLAB.NS" },
    { id: 39, name: "IndusInd Bank Ltd.", yfinName: "INDUSINDBK.NS" },
    { id: 40, name: "Eicher Motors Ltd.", yfinName: "EICHERMOT.NS" },
    { id: 41, name: "Adani Green Energy Ltd.", yfinName: "ADANIGREEN.NS" },
    { id: 42, name: "Shree Cement Ltd.", yfinName: "SHREECEM.NS" },
    { id: 43, name: "Tata Power Co. Ltd.", yfinName: "TATAPOWER.NS" },
    { id: 44, name: "Dr. Lal PathLabs Ltd.", yfinName: "LALPATHLAB.NS" },
    { id: 45, name: "Bharat Petroleum Corporation Ltd.", yfinName: "BPCL.NS" },
    { id: 46, name: "Mahindra LifeSpaces Developers Ltd.", yfinName: "MAHLIFE.NS" },
    { id: 47, name: "Adani Transmission Ltd.", yfinName: "ADANITRANS.NS" },
    { id: 48, name: "SBI Life Insurance Co. Ltd.", yfinName: "SBILIFE.NS" },
    { id: 49, name: "Muthoot Finance Ltd.", yfinName: "MUTHOOTFIN.NS" },
    { id: 50, name: "Tata Chemicals Ltd.", yfinName: "TATACHEM.NS" },
    { id: 51, name: "Sundaram Clayton Ltd.", yfinName: "SUNDCLAY.NS" },
    { id: 52, name: "Piramal Enterprises Ltd.", yfinName: "PIRAMAL.NS" },
    { id: 53, name: "Godrej Consumer Products Ltd.", yfinName: "GODREJCP.NS" },
    { id: 54, name: "Colgate-Palmolive (India) Ltd.", yfinName: "COLPAL.NS" },
    { id: 55, name: "HDFC Asset Management Co. Ltd.", yfinName: "HDFCAMC.NS" },
    { id: 56, name: "Kotak Mahindra Life Insurance Co. Ltd.", yfinName: "KOTAKLIFE.NS" },
    { id: 57, name: "ICICI Lombard General Insurance Co. Ltd.", yfinName: "ICICIGI.NS" },
    { id: 58, name: "Kotak Mahindra Bank Ltd.", yfinName: "KOTAKBANK.NS" },
    { id: 59, name: "ICICI Prudential Life Insurance Co. Ltd.", yfinName: "ICICIPRULI.NS" },
    { id: 60, name: "Hindustan Zinc Ltd.", yfinName: "HINDZINC.NS" },
    { id: 61, name: "Nestle India Ltd.", yfinName: "NESTLEIND.NS" },
    { id: 62, name: "Bajaj Holdings & Investment Ltd.", yfinName: "BAJAJHLDNG.NS" },
    { id: 63, name: "Hero MotoCorp Ltd.", yfinName: "HEROMOTOCO.NS" },
    { id: 64, name: "Lupin Ltd.", yfinName: "LUPIN.NS" },
    { id: 65, name: "Tata Elxsi Ltd.", yfinName: "TATAELXSI.NS" },
    { id: 66, name: "Mindtree Ltd.", yfinName: "MINDTREE.NS" },
    { id: 67, name: "Patanjali Ayurved Ltd.", yfinName: "PATANJALI.NS" },
    { id: 68, name: "Max Financial Services Ltd.", yfinName: "MAXFINANCIAL.NS" },
    { id: 69, name: "Adani Enterprises Ltd.", yfinName: "ADANIENT.NS" },
    { id: 70, name: "Muthoot Finance Ltd.", yfinName: "MUTHOOTFIN.NS" },
    { id: 71, name: "Bandhan Bank Ltd.", yfinName: "BANDHANBANK.NS" },
    { id: 72, name: "Ambuja Cements Ltd.", yfinName: "AMBUJACEM.NS" },
    { id: 73, name: "Cement Corporation of India Ltd.", yfinName: "CCI.NS" },
    { id: 74, name: "Indian Oil Corporation Ltd.", yfinName: "IOC.NS" },
    { id: 75, name: "UPL Ltd.", yfinName: "UPL.NS" },
    { id: 76, name: "Indiabulls Housing Finance Ltd.", yfinName: "IBULHSGFIN.NS" },
    { id: 77, name: "Bank of Baroda", yfinName: "BANKBARODA.NS" },
    { id: 78, name: "NTPC Ltd.", yfinName: "NTPC.NS" },
    { id: 79, name: "GAIL (India) Ltd.", yfinName: "GAIL.NS" },
    { id: 80, name: "Torrent Pharmaceuticals Ltd.", yfinName: "TORNTPHARM.NS" },
    { id: 81, name: "Apollo Hospitals Enterprise Ltd.", yfinName: "APOLLOHOSP.NS" },
    { id: 82, name: "Ambuja Cements Ltd.", yfinName: "AMBUJACEM.NS" },
    { id: 83, name: "Cipla Ltd.", yfinName: "CIPLA.NS" },
    { id: 84, name: "Adani Transmission Ltd.", yfinName: "ADANITRANS.NS" },
    { id: 85, name: "Tata Steel Ltd.", yfinName: "TATASTEEL.NS" },
    { id: 86, name: "Mahindra & Mahindra Ltd.", yfinName: "M&M.NS" },
    { id: 87, name: "Zee Entertainment Enterprises Ltd.", yfinName: "ZEEL.NS" },
    { id: 88, name: "TVS Motor Company Ltd.", yfinName: "TVSMOTOR.NS" },
    { id: 89, name: "Bharat Forge Ltd.", yfinName: "BHARATFORG.NS" },
    { id: 90, name: "Cognizant Technology Solutions Corp.", yfinName: "CTSH.NS" },
    { id: 91, name: "HCL Technologies Ltd.", yfinName: "HCLTECH.NS" },
    { id: 92, name: "Wipro Ltd.", yfinName: "WIPRO.NS" },
    { id: 93, name: "Cement Corporation of India Ltd.", yfinName: "CCI.NS" },
    { id: 94, name: "Hindalco Industries Ltd.", yfinName: "HINDALCO.NS" },
    { id: 95, name: "Reliance Infrastructure Ltd.", yfinName: "RELINFRA.NS" },
    { id: 96, name: "United Breweries Ltd.", yfinName: "UBER.NS" },
    { id: 97, name: "Hindustan Zinc Ltd.", yfinName: "HINDZINC.NS" },
    { id: 98, name: "Tata Global Beverages Ltd.", yfinName: "TATAGLOBAL.NS" },
    { id: 99, name: "Mphasis Ltd.", yfinName: "MPHASIS.NS" },
    { id: 100, name: "Exide Industries Ltd.", yfinName: "EXIDEIND.NS" },
    { id: 101, name: "HDFC Ltd.", yfinName: "HDFC.NS" },
    { id: 102, name: "Bajaj Finserv Ltd.", yfinName: "BAJAJFINSV.NS" },
    { id: 103, name: "Maruti Suzuki India Ltd.", yfinName: "MARUTI.NS" },
    { id: 104, name: "Axis Bank Ltd.", yfinName: "AXISBANK.NS" },
    { id: 105, name: "Hero MotoCorp Ltd.", yfinName: "HEROMOTOCO.NS" },
    { id: 106, name: "Mahindra & Mahindra Ltd.", yfinName: "M&M.NS" },
    { id: 107, name: "ICICI Bank Ltd.", yfinName: "ICICIBANK.NS" },
    { id: 108, name: "Piramal Enterprises Ltd.", yfinName: "PIRAMAL.NS" },
    { id: 109, name: "Larsen & Toubro Ltd.", yfinName: "LT.NS" },
    { id: 110, name: "ITC Ltd.", yfinName: "ITC.NS" },
    { id: 111, name: "Bajaj Auto Ltd.", yfinName: "BAJAJ-AUTO.NS" },
    { id: 112, name: "Aarti Industries Ltd.", yfinName: "AARTIIND.NS" },
    { id: 113, name: "Reliance Power Ltd.", yfinName: "RELIANCEP.NS" },
    { id: 114, name: "Indian Oil Corporation Ltd.", yfinName: "IOC.NS" },
    { id: 115, name: "NTPC Ltd.", yfinName: "NTPC.NS" },
    { id: 116, name: "Reliance Infrastructure Ltd.", yfinName: "RELINFRA.NS" },
    { id: 117, name: "Muthoot Finance Ltd.", yfinName: "MUTHOOTFIN.NS" },
    { id: 118, name: "Sun Pharmaceutical Industries Ltd.", yfinName: "SUNPHARMA.NS" },
    { id: 119, name: "Oberoi Realty Ltd.", yfinName: "OBEROIRLTY.NS" },
    { id: 120, name: "SBI Life Insurance Co. Ltd.", yfinName: "SBILIFE.NS" },
    { id: 121, name: "Nippon Life India Asset Management", yfinName: "NAM.NS" },
    { id: 122, name: "Mahindra & Mahindra Ltd.", yfinName: "M&M.NS" },
    { id: 123, name: "Indian Hotels Company Ltd.", yfinName: "INDHOTEL.NS" },
    { id: 124, name: "Vedanta Ltd.", yfinName: "VEDL.NS" },
    { id: 125, name: "ICICI Lombard General Insurance Co. Ltd.", yfinName: "ICICIGI.NS" },
    { id: 126, name: "Zydus Wellness Ltd.", yfinName: "ZYDUSWELL.NS" },
    { id: 127, name: "HDFC Asset Management Co. Ltd.", yfinName: "HDFCAMC.NS" },
    { id: 128, name: "Tech Mahindra Ltd.", yfinName: "TECHM.NS" },
    { id: 129, name: "Avenue Supermarts Ltd.", yfinName: "DMART.NS" },
    { id: 130, name: "Godrej Consumer Products Ltd.", yfinName: "GODREJCP.NS" },
    { id: 131, name: "Shree Cement Ltd.", yfinName: "SHREECEM.NS" },
    { id: 132, name: "ICICI Prudential Life Insurance Co. Ltd.", yfinName: "ICICIPRULI.NS" },
    { id: 133, name: "Hindustan Zinc Ltd.", yfinName: "HINDZINC.NS" },
    { id: 134, name: "Bharat Forge Ltd.", yfinName: "BHARATFORG.NS" },
    { id: 135, name: "ICICI Bank Ltd.", yfinName: "ICICIBANK.NS" },
    { id: 136, name: "Tata Consultancy Services Ltd.", yfinName: "TCS.NS" },
    { id: 137, name: "Wipro Ltd.", yfinName: "WIPRO.NS" },
    { id: 138, name: "Hindalco Industries Ltd.", yfinName: "HINDALCO.NS" },
    { id: 139, name: "Tata Steel Ltd.", yfinName: "TATASTEEL.NS" },
    { id: 140, name: "Asian Paints Ltd.", yfinName: "ASIANPAINT.NS" },
    { id: 141, name: "Mphasis Ltd.", yfinName: "MPHASIS.NS" },
    { id: 142, name: "Bajaj Finance Ltd.", yfinName: "BAJFINANCE.NS" },
    { id: 143, name: "Reliance Industries Ltd.", yfinName: "RELIANCE.NS" },
    { id: 144, name: "Tata Motors Ltd.", yfinName: "TATAMOTORS.NS" },
    { id: 145, name: "Axis Bank Ltd.", yfinName: "AXISBANK.NS" },
    { id: 146, name: "Kotak Mahindra Bank Ltd.", yfinName: "KOTAKBANK.NS" },
    { id: 147, name: "Hindustan Unilever Ltd.", yfinName: "HINDUNILVR.NS" },
    { id: 148, name: "ITC Ltd.", yfinName: "ITC.NS" },
    { id: 149, name: "Sun Pharmaceutical Industries Ltd.", yfinName: "SUNPHARMA.NS" },
    { id: 150, name: "Bajaj Auto Ltd.", yfinName: "BAJAJ-AUTO.NS" },
    { id: 151, name: "State Bank of India", yfinName: "SBIN.NS" },
    { id: 152, name: "Tata Power Co. Ltd.", yfinName: "TATAPOWER.NS" },
    { id: 153, name: "Tata Consultancy Services Ltd.", yfinName: "TCS.NS" },
    { id: 154, name: "SBI Life Insurance Co. Ltd.", yfinName: "SBILIFE.NS" },
    { id: 155, name: "Hero MotoCorp Ltd.", yfinName: "HEROMOTOCO.NS" },
    { id: 156, name: "ICICI Prudential Life Insurance Co. Ltd.", yfinName: "ICICIPRULI.NS" },
    { id: 157, name: "Wipro Ltd.", yfinName: "WIPRO.NS" },
    { id: 158, name: "Bharat Petroleum Corporation Ltd.", yfinName: "BPCL.NS" },
    { id: 159, name: "HCL Technologies Ltd.", yfinName: "HCLTECH.NS" },
    { id: 160, name: "Dr. Reddy's Laboratories Ltd.", yfinName: "DRREDDY.NS" },
    { id: 161, name: "Shree Cement Ltd.", yfinName: "SHREECEM.NS" },
    { id: 162, name: "Tech Mahindra Ltd.", yfinName: "TECHM.NS" },
    { id: 163, name: "Cipla Ltd.", yfinName: "CIPLA.NS" },
    { id: 164, name: "Bajaj Finserv Ltd.", yfinName: "BAJAJFINSV.NS" },
    { id: 165, name: "Bajaj Finance Ltd.", yfinName: "BAJFINANCE.NS" },
    { id: 166, name: "State Bank of India", yfinName: "SBIN.NS" },
    { id: 167, name: "Zee Entertainment Enterprises Ltd.", yfinName: "ZEEL.NS" },
    { id: 168, name: "Muthoot Finance Ltd.", yfinName: "MUTHOOTFIN.NS" },
    { id: 169, name: "Sundaram Clayton Ltd.", yfinName: "SUNDCLAY.NS" },
    { id: 170, name: "IndusInd Bank Ltd.", yfinName: "INDUSINDBK.NS" },
    { id: 171, name: "Axis Bank Ltd.", yfinName: "AXISBANK.NS" },
    { id: 172, name: "Reliance Industries Ltd.", yfinName: "RELIANCE.NS" },
    { id: 173, name: "Hindustan Zinc Ltd.", yfinName: "HINDZINC.NS" },
    { id: 174, name: "HDFC Bank Ltd.", yfinName: "HDFCBANK.NS" },
    { id: 175, name: "Bharat Forge Ltd.", yfinName: "BHARATFORG.NS" },
    { id: 176, name: "SBI Life Insurance Co. Ltd.", yfinName: "SBILIFE.NS" },
    { id: 177, name: "Muthoot Finance Ltd.", yfinName: "MUTHOOTFIN.NS" },
    { id: 178, name: "ICICI Bank Ltd.", yfinName: "ICICIBANK.NS" },
    { id: 179, name: "Kotak Mahindra Bank Ltd.", yfinName: "KOTAKBANK.NS" },
    { id: 180, name: "HDFC Ltd.", yfinName: "HDFC.NS" },
    { id: 181, name: "IndusInd Bank Ltd.", yfinName: "INDUSINDBK.NS" },
    { id: 182, name: "Hindustan Unilever Ltd.", yfinName: "HINDUNILVR.NS" },
    { id: 183, name: "Bajaj Finance Ltd.", yfinName: "BAJFINANCE.NS" },
    { id: 184, name: "Infosys Ltd.", yfinName: "INFY.NS" },
    { id: 185, name: "ICICI Bank Ltd.", yfinName: "ICICIBANK.NS" },
    { id: 186, name: "Wipro Ltd.", yfinName: "WIPRO.NS" },
    { id: 187, name: "Tata Steel Ltd.", yfinName: "TATASTEEL.NS" },
    { id: 188, name: "Cipla Ltd.", yfinName: "CIPLA.NS" },
    { id: 189, name: "Sun Pharmaceutical Industries Ltd.", yfinName: "SUNPHARMA.NS" },
    { id: 190, name: "Larsen & Toubro Ltd.", yfinName: "LT.NS" },
    { id: 191, name: "Axis Bank Ltd.", yfinName: "AXISBANK.NS" },
    { id: 192, name: "Bajaj Finserv Ltd.", yfinName: "BAJAJFINSV.NS" },
    { id: 193, name: "Tata Consultancy Services Ltd.", yfinName: "TCS.NS" },
    { id: 194, name: "ICICI Prudential Life Insurance Co. Ltd.", yfinName: "ICICIPRULI.NS" },
    { id: 195, name: "ICICI Lombard General Insurance Co. Ltd.", yfinName: "ICICIGI.NS" },
    { id: 196, name: "Mahindra & Mahindra Ltd.", yfinName: "M&M.NS" },
    { id: 197, name: "Hindustan Zinc Ltd.", yfinName: "HINDZINC.NS" },
    { id: 198, name: "Bajaj Finance Ltd.", yfinName: "BAJFINANCE.NS" },
    { id: 199, name: "ICICI Bank Ltd.", yfinName: "ICICIBANK.NS" },
    { id: 200, name: "Reliance Industries Ltd.", yfinName: "RELIANCE.NS" }
]

export default stockData;